### ISSUE TITLE
Armazém GRP não retorna dados

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/de-para-sigplan-grp#1]
@fjuniorr tentei gerar a consulta no armazém GRP referente a `orcamentogeraluniao.csv` com as variáveis que identifiquei, mas não retornou resultado.
Filtrei por ano de exercício 2023. Deixei salva a consulta na pasta da AID no armazém.

![image](https://github.com/user-attachments/assets/f6cce163-3962-4575-a21f-743a588956cd)

**Comment by fjuniorr** [comment]
Os dados do Armazém GRP são do ambiente de operação assistida. Não vão existir dados para o exercício de 2023.

**Comment by hslinhares** [comment]
Retirei o filtro e dupliquei a consulta pra não misturar dados de execução com restos a pagar. Ainda assim estão vindo com problema.
`Execução:`

![image](https://github.com/user-attachments/assets/e0db9c0f-d2b0-42de-b6f7-df9fb2628a2e)

![image](https://github.com/user-attachments/assets/a0157644-bed5-402f-823d-9f69dddf93bf)


`Restos a pagar:`

![image](https://github.com/user-attachments/assets/c17ca747-5db1-4965-a1fa-96e7c4d0a2ac)

**Comment by fjuniorr** [comment]
[Objetos da assuntos diferentes](https://www.armazem.mg.gov.br/index.php/duvidas) não devem ser mesclados na consulta, não somente no relatório.
